# Numpy
    --> Numpy is a Linear Algebra Library For Python, The Reason It Is so Important For Data Science With Python Is That Almost All Of The Libraries In The PyData EcoSystem Rely On Numpy As One Of Their Main Building Blocks.
    --> Numpy Is Also Incredibly Fast, As It Has Bindings To 'C' Libraries.

# Numpy Arrays

### Numpy Arrays are The Main Way We Use.
### Numpy Arrays Essentially Come In Two Flavors: Vectors and Matrices.
### Vectors Are Stricktly 1-d Arrays and Matrices are 2-d (but note that a matrix can still have only one row or one column).

In [1]:
import numpy as np

## Creating Numpy From Array From Python List

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
arr.dtype

dtype('int32')

In [5]:
my_mat = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating Numpy Arrays Using Numpy Library Methods

In [7]:
# Similar To Python range()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(0, 50, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [10]:
# Creating Array of Zeros
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3, 4)) # (Rows, Columns)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Creating Array of Ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
# Generating 10 Evenly Space Points Between 0 and 5.
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
# Generating 100 Evenly Space Points Between 0 and 10.
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [16]:
# Creating Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Generating Arrays of Random Data

In [17]:
# Create Array of Given Shape From The Sample of Uniform Distribution Between 0 and 1.
np.random.rand(5)

array([0.84658887, 0.61277473, 0.9168992 , 0.71936544, 0.76076746])

In [18]:
np.random.rand(3, 5)

array([[0.94733471, 0.88760907, 0.31501152, 0.40088632, 0.56904969],
       [0.19409318, 0.10819188, 0.09591737, 0.16815798, 0.86784659],
       [0.82909548, 0.33091431, 0.99958532, 0.35897467, 0.00101498]])

In [19]:
# Create Array of Given Shape From The Sample of Noraml or Gaussian Distribution Between 0 and 1.
np.random.randn(2)

array([ 0.32626653, -0.50238546])

In [20]:
np.random.randn(3, 5)

array([[-0.78550033, -0.90184057,  0.95005939,  0.49830027,  0.88608049],
       [-0.6548655 , -0.85840006, -1.52458493,  1.06601354, -0.77428733],
       [-0.57661029, -2.17213969,  1.57462082, -0.65402125, -0.1056978 ]])

In [21]:
# Generate Random Number or Array of Numbers Between Specified low and high parameter.
# Third Parameter is size, by setting it we can get required number of random integers.
# low -> Inclusive, high -> Exclusive.
np.random.randint(1, 100)

56

In [22]:
np.random.randint(1, 100, 10)

array([11, 36, 17, 67,  1, 91,  3, 27, 63, 20])

## Reshaping Array

In [23]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([35, 39, 21, 41, 32, 40, 45, 16, 44, 44])

In [25]:
# rows * column must be equal to available elements in array.
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.reshape(2, 5)

array([[35, 39, 21, 41, 32],
       [40, 45, 16, 44, 44]])

In [27]:
ranarr.reshape(5, 2)

array([[35, 39],
       [21, 41],
       [32, 40],
       [45, 16],
       [44, 44]])

## Some Important Methods & Attributes

In [28]:
# Return Maximum Value of Array
ranarr.max()

45

In [29]:
# Return Minimum Value of Array
ranarr.min()

16

In [30]:
# Return Position(Index) of Maximum Value
ranarr.argmax()

6

In [31]:
# Return Position(Index) of Minimum Value
ranarr.argmin()

7

In [32]:
# Return Shape of An Array
arr.shape

(25,)

In [33]:
# Return What Kind of Data Array is Holding
arr.dtype

dtype('int32')