# Numpy Indexing And Selection

In [1]:
import numpy as np;

## Indexing An Array

In [2]:
np.random.seed(10)
arr = np.random.randint(0, 11, 10)
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [3]:
arr[8]

8

In [4]:
arr[3:6]

array([1, 9, 0])

In [5]:
arr[:6]

array([9, 4, 0, 1, 9, 0])

In [6]:
arr[3:]

array([ 1,  9,  0,  1, 10,  8,  9])

In [7]:
arr[::2]

array([9, 0, 9, 1, 8])

In [8]:
arr[::-1]

array([ 9,  8, 10,  1,  0,  9,  1,  0,  4,  9])

## Broadcasting

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   0,   1,  10,   8,   9])

In [11]:
np.random.seed(10)
arr = np.random.randint(0, 11, 10)
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [12]:
slice_of_array = arr[0:6]
slice_of_array

array([9, 4, 0, 1, 9, 0])

In [13]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  1, 10,  8,  9])

In [15]:
# Original Array Also Changes Because Arrays Are Reference Types assigning an array or slice of an array to a variable directly gives the pointer of that array not the copy of the array

In [16]:
np.random.seed(10)
arr = np.random.randint(0, 11, 10)
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [17]:
arr_copy = arr.copy()
arr_copy

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [18]:
arr_copy[:6] = 155
arr_copy

array([155, 155, 155, 155, 155, 155,   1,  10,   8,   9])

In [19]:
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [20]:
# Here Original Array Did Not Mutate Because We Cloned The Original Array Instead of Passing The Pointer.

## Indexing A 2-d Array

In [21]:
arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d[0][0]

5

In [23]:
arr_2d[2][1]

40

In [24]:
# Alternate Syntax To Use Indexing In 2d-Arrays
arr_2d[2, 1]

40

In [25]:
# Creating Sub-Matrices From Matrix
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [26]:
arr_2d[1: , 1:]

array([[25, 30],
       [40, 45]])

In [27]:
arr_2d[1: , :2]

array([[20, 25],
       [35, 40]])

In [28]:
arr_2d[:, :1]

array([[ 5],
       [20],
       [35]])

## Conditional Selection

In [29]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [32]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [33]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr == 5]

array([5])

In [35]:
arr[arr < 8]

array([1, 2, 3, 4, 5, 6, 7])