# Numpy Indexing And Selection

In [49]:
import numpy as np;

## Indexing An Array

In [50]:
np.random.seed(10)
arr = np.random.randint(0, 11, 10)
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [51]:
arr[8]

8

In [52]:
arr[3:6]

array([1, 9, 0])

In [53]:
arr[:6]

array([9, 4, 0, 1, 9, 0])

In [54]:
arr[3:]

array([ 1,  9,  0,  1, 10,  8,  9])

In [55]:
arr[::2]

array([9, 0, 9, 1, 8])

In [56]:
arr[::-1]

array([ 9,  8, 10,  1,  0,  9,  1,  0,  4,  9])

## Broadcasting

In [57]:
arr[0:5] = 100

In [58]:
arr

array([100, 100, 100, 100, 100,   0,   1,  10,   8,   9])

In [61]:
np.random.seed(10)
arr = np.random.randint(0, 11, 10)
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [62]:
slice_of_array = arr[0:6]
slice_of_array

array([9, 4, 0, 1, 9, 0])

In [63]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [64]:
arr

array([99, 99, 99, 99, 99, 99,  1, 10,  8,  9])

In [65]:
# Original Array Also Changes Because Arrays Are Reference Types assigning an array or slice of an array to a variable directly gives the pointer of that array not the copy of the array

In [66]:
np.random.seed(10)
arr = np.random.randint(0, 11, 10)
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [67]:
arr_copy = arr.copy()
arr_copy

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [68]:
arr_copy[:6] = 155
arr_copy

array([155, 155, 155, 155, 155, 155,   1,  10,   8,   9])

In [69]:
arr

array([ 9,  4,  0,  1,  9,  0,  1, 10,  8,  9])

In [70]:
# Here Original Array Did Not Mutate Because We Cloned The Original Array Instead of Passing The Pointer.

## Indexing A 2-d Array

In [71]:
arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[0][0]

5

In [73]:
arr_2d[2][1]

40

In [75]:
# Alternate Syntax To Use Indexing In 2d-Arrays
arr_2d[2, 1]

40

In [77]:
# Creating Sub-Matrices From Matrix
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [78]:
arr_2d[1: , 1:]

array([[25, 30],
       [40, 45]])

In [80]:
arr_2d[1: , :2]

array([[20, 25],
       [35, 40]])

In [82]:
arr_2d[:, :1]

array([[ 5],
       [20],
       [35]])

## Conditional Selection

In [83]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [85]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [86]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [87]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [88]:
arr[arr == 5]

array([5])

In [91]:
arr[arr < 8]

array([1, 2, 3, 4, 5, 6, 7])